version: '3'
services:
  wol:
    image: ghcr.io/yude/go-rest-wol
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: "./hosts.csv"
        target: "/app/hosts.csv"

networks:
  default:
    external:
      name: nat